---
title: "otus_ratio_relationship"
author: "Xinyi Lin"
date: "3/4/2020"
output: html_document
---

```{r,message=FALSE}
library(dplyr)
library(ggplot2)
```

```{r}
x = seq(0,4,0.1)
y = -1/2*(x-2)^2+6
z = -2*(x-2)^2+8   # higher growth rate
curve = data.frame(x,y = c(y,z), y_index = as.factor(c(rep("y",41),rep("z"，41))))
curve %>% 
  ggplot(aes(x,y)) +
  geom_point(aes(color = y_index))
```

```{r}
a1 = 3
a2 = 2
a3 = 1
b1 = 0.5
b2 = 3.5
# 3, 2, 1 is type a 16s, 0.5, 3.5 is type b 16s
ya1 = -1/2*(a1-2)^2+6
ya2 = -1/2*(a2-2)^2+6
ya3 = -1/2*(a3-2)^2+6
yb1 = -1/2*(b1-2)^2+6
yb2 = -1/2*(b2-2)^2+6
za1 = -2*(a1-2)^2+8
za2 = -2*(a2-2)^2+8
za3 = -2*(a3-2)^2+8
zb1 = -2*(b1-2)^2+8
zb2 = -2*(b2-2)^2+8
(za1+za2+za3)/(zb1+zb2)
(ya1+ya2+ya3)/(yb1+yb2)
```

```{r}
ComRatio = function(ab_vec){
  a1 = ab_vec[1]
  a2 = ab_vec[2]
  a3 = ab_vec[3]
  b1 = ab_vec[4]
  b2 = ab_vec[5]
  ya1 = -1/2*(a1-2)^2+6
  ya2 = -1/2*(a2-2)^2+6
  ya3 = -1/2*(a3-2)^2+6
  yb1 = -1/2*(b1-2)^2+6
  yb2 = -1/2*(b2-2)^2+6
  za1 = -2*(a1-2)^2+8
  za2 = -2*(a2-2)^2+8
  za3 = -2*(a3-2)^2+8
  zb1 = -2*(b1-2)^2+8
  zb2 = -2*(b2-2)^2+8
  za = (za1+za2+za3)/3
  zb = (zb1+zb2)/2
  ya = (ya1+ya2+ya3)/3
  yb = (yb1+yb2)/2
  if (za > zb) {
    zRatio = za/zb
    yRatio = ya/yb}
  else {
    zRatio = za/zb
    yRatio = ya/yb
  }
  res = data.frame(A1 = a1, A2 = a2, A3 = a3, B1 = b1, B2 = b2, zRatio = zRatio, yRatio = yRatio)
  return(res)  # first one is the higher growth rate
} 
```

```{r}
ComRatio2 = function(a_vec, b_vec){
  ya = -1/2*(a_vec-2)^2+6
  yb = -1/2*(b_vec-2)^2+6
  za = -2*(a_vec-2)^2+8
  zb = -2*(b_vec-2)^2+8
  res = c(a_vec, b_vec, sum(za)/sum(zb), sum(ya)/sum(yb))
  return(res)  # first one is the higher growth rate
} 
a_vec = runif(3,0,4)
b_vec = runif(2,0,4)
ComRatio2(a_vec, b_vec)
```

```{r}
ran_ab = runif(5,0,4)
res20 = ComRatio(ran_ab)
for (i in 1:20) {
  ran_ab = runif(5,0,4)
  res20 = rbind(res20,ComRatio(ran_ab))
}
res20
```

```{r}
x = seq(0,4,0.1)
y = -1/2*(x-2)^2+6
z = -2*(x-2)^2+8   # higher growth rate
curve = data.frame(x,y = c(y,z), y_index = as.factor(c(rep("y",41),rep("z"，41))))
curve %>% 
  ggplot(aes(x,y)) +
  geom_point(aes(color = y_index)) + 
  geom_vline(aes(xintercept=res20[2,1], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,2], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,3], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,4])) +
  geom_vline(aes(xintercept=res20[2,5])) 
```

##

```{r}
by = function(x){
  sapply(x, function(x) {
  if (x<1) 
    y = 1/2*x + 3
  else if (x>=1 & x<3) 
    y = -1/2*x + 4
  else
    y = 1/2*x + 1
  return(y)
  })
}

bz = function(x){
  sapply(x, function(x) {
  if (x<1) 
    y = 2*x + 3
  else if (x>=1 & x<3) 
    y = -2*x + 7
  else
    y = 2*x - 5
  return(y)
  })
}
```

```{r}
x = seq(0,4,0.1)
y = by(x)
z = bz(x)   # higher growth rate
curve = data.frame(x,y = c(y,z), y_index = as.factor(c(rep("y",41),rep("z"，41))))
curve %>% 
  ggplot(aes(x,y)) +
  geom_point(aes(color = y_index))
```

```{r}
ComRatio = function(ab_vec){
  a = ab_vec[1:3]
  b = ab_vec[4:5]
  ya = sum(by(a))/3
  za = sum(bz(a))/3
  yb = sum(by(b))/2
  zb = sum(bz(b))/2
  if (za > zb) {
    zR = za/zb
    yR = ya/yb
    } else {
    zR = zb/za
    yR = yb/ya
  }
  res = data.frame(A1 = a[1], A2 = a[2], A3 = a[3], B1 = b[1], B2 = b[2], zRatio = zR, yRatio = yR)
  return(res)  # first one is the higher growth rate
}
```

```{r}
ran_ab = runif(5,0,4)
res20 = ComRatio(ran_ab)
for (i in 1:20) {
  ran_ab = runif(5,1,3)
  res20 = rbind(res20,ComRatio(ran_ab))
}
res20 %>% 
  filter(zRatio <= yRatio)
```

```{r}
x = seq(0,4,0.1)
y = by(x)
z = bz(x)   # higher growth rate
curve = data.frame(x,y = c(y,z), y_index = as.factor(c(rep("y",41),rep("z"，41))))
curve %>% 
  ggplot(aes(x,y)) +
  geom_point(aes(color = y_index)) + 
  geom_vline(aes(xintercept=res20[2,1], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,2], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,3], color = "#990000")) +
  geom_vline(aes(xintercept=res20[2,4])) +
  geom_vline(aes(xintercept=res20[2,5]))
```

```{r}
sum(by(res20[2,1:3]))/3
by(sum(res20[2,1:3])/3)
sum(bz(res20[2,1:3]))/3
bz(sum(res20[2,1:3])/3)
sum(by(res20[2,4:5]))/2
by(sum(res20[2,4:5])/2)
sum(bz(res20[2,4:5]))/2
bz(sum(res20[2,4:5])/2)
```


